FROM     ubuntu
USER     bin

RUN     useradd todo
RUN     mkdir /todo && chown=todo:todo /todo -R
USER    todo
WORKDIR /todo




#git pull ; docker build -t 11user . ; docker run --rm 11user id    / pwd 