# kill -l (shows all signals in our operating system)

FROM            ubuntu
STOPSIGNAL      SIGINT
CMD             ["sleep","100" ]


# docker build -t 14stopsignal .
# docker run -d 14stopsignal
# docker ps -a

# catch signals "trap" google reference dds

