FROM        ubuntu
ARG         URL
ENV         URL=${URL}




# git pul
# docker build -t 12args .
# docker run --rm 12args env
# docker build --build-arg URL=zelarsoft.com -t 12args .
# docker run --rm 12args env

# here you can paramenterize your docker file , we use varaibles inside your docker file 
