FROM            ubuntu
RUN             mkdir /myvol
RUN             echo "Good Afternoon ZelarSoft Team" > /myvol/greeting
VOLUME          /myvol


# git pull ; docker build -t 10volumes . ; docker run --rm 10volumes df -h
# git pull ; docker build -t 10volumes . ; docekr run --rm 10volumes ls /myvol    then cat /myvol/greeting