FROM        ubuntu
RUN         apt update -y   
RUN         apt install nginx -y
CMD         ["nginx", "-g", "daemon off;"]
LABEL       company="zelarsoft" \
            employeename="sreenath r" \
            role="trainne"
EXPOSE      80/tcp     
       
ENV         MY_NAME="sreenath"
ENV         URL=zelarsoft.com