FROM        ubuntu
RUN         apt update -y
RUN         apt install iputils-ping -y
ENTRYPOINT  ["ping", "-c", "2"]
CMD         [ "zelarsoft.com" ]


# docker run --rm 09entrypoint&cmd 
# docker run --rm 09entrypoint&cmd  google.com